# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        macos:
          - 11
          - 12
        xcode:
          - latest-stable
        include:
          - macos: 11
            xcode: latest
    runs-on: macos-${{ matrix.macos }}
    steps:
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run:
          xcodebuild -scheme Localizer -sdk macosx clean build test -destination "platform=macOS"
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          # the token is optional for a public repo, but including it anyway
          token: b705013a-611b-44ed-ba4c-20540005b523
          env_vars: MD_APPLE_SDK_ROOT,RUNNER_OS,RUNNER_ARCH
