# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        macos:
          - 12
        xcode:
          - latest-stable
        include:
          - macos: 12
            xcode: latest
    runs-on: macos-${{ matrix.macos }}
    steps:
      - name: Get Sources
        uses: actions/checkout@v2
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.0
        with:
          xcode-version: "14.2"

      - name: Build Package
        run: swift build -v

      - name: Run tests
        run: swift test
